# Generated by Django 2.2.2 on 2019-06-06 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('index', models.IntegerField(default=0)),
                ('stating_in_seconds', models.FloatField(default=0.0)),
                ('duration_in_seconds', models.FloatField(default=0.0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jump_tube.Video')),
            ],
        ),
    ]
