# Generated by Django 2.2.2 on 2019-06-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0002_auto_20190606_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
    ]
