# Generated by Django 2.2.2 on 2019-06-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0003_remove_video_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='movie_url',
            new_name='url',
        ),
    ]
