# Generated by Django 2.2.2 on 2019-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0004_auto_20190606_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='offset_seconds',
        ),
        migrations.AddField(
            model_name='video',
            name='from_file',
            field=models.FileField(blank=True, default=None, max_length=100000000000, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
