# Generated by Django 2.2.2 on 2019-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0005_auto_20190611_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='srt_file',
            field=models.FileField(blank=True, default=None, max_length=100000000, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
