# Generated by Django 2.2.2 on 2019-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0006_video_srt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
