# Generated by Django 2.2.2 on 2019-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0007_auto_20190613_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='fov',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='roll',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='yaw',
            field=models.FloatField(default=0.0),
        ),
    ]
