# Generated by Django 2.2.2 on 2019-06-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0008_auto_20190614_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='picture',
            field=models.ImageField(blank=True, default=None, max_length=100000000, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
