# Generated by Django 2.2.2 on 2019-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0009_subtitle_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='picture',
            field=models.ImageField(blank=True, default=None, max_length=100000000, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
