# Generated by Django 2.2.2 on 2019-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0010_video_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='picture',
            new_name='thumbnail',
        ),
    ]
