# Generated by Django 2.2.2 on 2019-06-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0011_auto_20190615_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fov',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='video',
            name='pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='roll',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='yaw',
            field=models.FloatField(default=0.0),
        ),
    ]
