# Generated by Django 2.2.2 on 2019-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_tube', '0012_auto_20190616_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='stating_in_seconds',
            new_name='starting_in_seconds',
        ),
        migrations.AddField(
            model_name='video',
            name='starting_in_seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
